### ISSUE TITLE
[feat] 습관 설정 시 요일, 시간을 추가

### ISSUE THREAD

**Issue by kimdouk** [New-Tine/New-Tine-Server#58]
## Description
>습관 설정할 때, 읽을 시간과 알림 시간 설정을 추가한다.

## TODO
- [ ] Habit 엔티티 수정
- [ ] HabitService, Controller 수정
- [ ] request DTO 추가

## ETC
기타사항
