### ISSUE TITLE
[feat] 특정 뉴스기사 스크랩 기능, 스크랩 취소 기능, 스크랩한 뉴스기사 조회 API 구현

### ISSUE THREAD

**Issue by jhjalison01** [New-Tine/New-Tine-Server#8]
## Description
>뉴스기사를 스크랩 했을 때 뉴스기사를 저장, 스크랩을 취소했을 때 뉴스기사를 삭제, 스크랩한 뉴스기사를 조회하는 API를 구현한다.

## TODO
- [x] getByNewsIdAndUserId 메소드 구현
- [x] 스크랩한 뉴스기사 저장 기능 구현
- [x] 스크랩을 취소했을 때 뉴스 기사 삭제 기능 구현
